In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("customer_churn_1000.csv")

In [3]:
df.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,ContractType,InternetService,TechSupport,PaymentMethod,MonthlyUsageGB,NumComplaints,Churn
0,1001,29,Female,9,60.41,543.69,One year,Fiber optic,Yes,Credit Card,164,0,No
1,1002,45,Female,56,88.60,4961.60,One year,DSL,Yes,Electronic Check,47,0,No
2,1003,22,Male,70,40.74,2851.80,One year,DSL,Yes,Cash,166,4,No
3,1004,35,Female,45,58.47,2631.15,One year,DSL,No,Credit Card,87,5,No
4,1005,39,Female,16,99.45,1591.20,Two year,DSL,No,Electronic Check,190,3,No

In [4]:
df.shape

(1000, 13)

In [5]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'MonthlyCharges',
       'TotalCharges', 'ContractType', 'InternetService', 'TechSupport',
       'PaymentMethod', 'MonthlyUsageGB', 'NumComplaints', 'Churn'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1000 non-null   int64
 1   Age              1000 non-null   int64
 2   Gender           999 non-null    object
 3   Tenure           1000 non-null   int64
 4   MonthlyCharges   1000 non-null   float64
 5   TotalCharges     1000 non-null   float64
 6   ContractType     1000 non-null   object
 7   InternetService  1000 non-null   object
 8   TechSupport      1000 non-null   object
 9   PaymentMethod    1000 non-null   object
 10  MonthlyUsageGB   1000 non-null   int64
 11  NumComplaints    1000 non-null   int64
 12  Churn            1000 non-null   object
dtypes: float64(2), int64(5), object(6)
memory usage: 101.7+ KB

In [7]:
df.isna().sum()

CustomerID         0
Age                0
Gender             1
Tenure             0
MonthlyCharges     0
TotalCharges       0
ContractType       0
InternetService    0
TechSupport        0
PaymentMethod      0
MonthlyUsageGB     0
NumComplaints      0
Churn              0
dtype: int64

In [9]:
df.describe()

,CustomerID,Age,Tenure,MonthlyCharges,TotalCharges,MonthlyUsageGB,NumComplaints
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1500.500000,43.025000,35.289000,81.179490,2858.690670,145.613000,2.444000
std,288.819436,13.046555,20.526491,22.697335,1905.919277,61.857899,1.712833
min,1001.000000,21.000000,1.000000,40.010000,55.850000,40.000000,0.000000
25%,1250.750000,32.000000,18.000000,61.497500,1330.035000,90.000000,1.000000
50%,1500.500000,43.000000,33.000000,82.135000,2584.690000,145.000000,2.500000
75%,1750.250000,54.000000,52.250000,100.530000,4118.625000,198.250000,4.000000
max,2000.000000,65.000000,72.000000,119.930000,8178.490000,250.000000,5.000000

In [10]:
df.duplicated().sum()

np.int64(0)