In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("customer_churn_clean.csv")

In [5]:
df.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,ContractType,InternetService,TechSupport,PaymentMethod,MonthlyUsageGB,NumComplaints,Churn
0,1001,29,Female,9,60.41,543.69,One year,Fiber optic,Yes,Credit Card,164,0,No
1,1002,45,Female,56,88.60,4961.60,One year,DSL,Yes,Electronic Check,47,0,No
2,1003,22,Male,70,40.74,2851.80,One year,DSL,Yes,Cash,166,4,No
3,1004,35,Female,45,58.47,2631.15,One year,DSL,No,Credit Card,87,5,No
4,1005,39,Female,16,99.45,1591.20,Two year,DSL,No,Electronic Check,190,3,No

In [6]:
df.dtypes

CustomerID           int64
Age                  int64
Gender              object
Tenure               int64
MonthlyCharges     float64
TotalCharges       float64
ContractType        object
InternetService     object
TechSupport         object
PaymentMethod       object
MonthlyUsageGB       int64
NumComplaints        int64
Churn               object
dtype: object

In [7]:
encoder = LabelEncoder()

In [8]:
df["Gender"] = encoder.fit_transform(df["Gender"])

df["ContractType"] = encoder.fit_transform(df["ContractType"])

df["InternetService"] = encoder.fit_transform(df["InternetService"])

df["TechSupport"] = encoder.fit_transform(df["TechSupport"])

df["PaymentMethod"] = encoder.fit_transform(df["PaymentMethod"])

df["Churn"] = encoder.fit_transform(df["Churn"])

In [9]:
df.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,ContractType,InternetService,TechSupport,PaymentMethod,MonthlyUsageGB,NumComplaints,Churn
0,1001,29,0,9,60.41,543.69,1,1,1,2,164,0,0
1,1002,45,0,56,88.60,4961.60,1,0,1,3,47,0,0
2,1003,22,1,70,40.74,2851.80,1,0,1,1,166,4,0
3,1004,35,0,45,58.47,2631.15,1,0,0,2,87,5,0
4,1005,39,0,16,99.45,1591.20,2,0,0,3,190,3,0

In [10]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [11]:
print(X.shape)

print(y.shape)

(1000, 12)
(1000,)

In [12]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [13]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,ContractType,InternetService,TechSupport,PaymentMethod,MonthlyUsageGB,NumComplaints
0,-1.730320,-1.075534,-0.984142,-1.281376,-0.915521,-1.215245,0.052963,1.008032,0.996008,0.447754,0.297395,-1.427590
1,-1.726856,0.151457,-0.984142,1.009494,0.327097,1.103909,0.052963,-0.992032,0.996008,1.337922,-1.594984,-1.427590
2,-1.723391,-1.612343,1.008048,1.691880,-1.782576,-0.003617,0.052963,-0.992032,0.996008,-0.442413,0.329743,0.908891
3,-1.719927,-0.615413,-0.984142,0.473333,-1.001036,-0.119446,0.052963,-0.992032,-1.004008,0.447754,-0.948017,1.493011
4,-1.716463,-0.308665,-0.984142,-0.940183,0.805366,-0.665361,1.284671,-0.992032,-1.004008,1.337922,0.717923,0.324771

In [14]:
X_scaled.describe()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,ContractType,InternetService,TechSupport,PaymentMethod,MonthlyUsageGB,NumComplaints
count,1000.00000,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03
mean,0.00000,1.136868e-16,-2.486900e-17,-7.460699e-17,5.755396e-16,2.131628e-17,3.907985e-17,1.065814e-17,8.881784e-17,-7.283063e-17,7.105427e-18,2.930989e-17
std,1.00050,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00
min,-1.73032,-1.689030e+00,-9.841419e-01,-1.671311e+00,-1.814755e+00,-1.471334e+00,-1.178744e+00,-9.920317e-01,-1.004008e+00,-1.332581e+00,-1.708203e+00,-1.427590e+00
25%,-0.86516,-8.454735e-01,-9.841419e-01,-8.426989e-01,-8.675837e-01,-8.024582e-01,-1.178744e+00,-9.920317e-01,-1.004008e+00,-6.649553e-01,-8.994943e-01,-8.434695e-01
50%,0.00000,-1.917174e-03,-9.841419e-01,-1.115702e-01,4.211896e-02,-1.438349e-01,5.296342e-02,-9.920317e-01,9.960080e-01,-4.424134e-01,-9.914768e-03,3.271073e-02
75%,0.86516,8.416392e-01,1.008048e+00,8.267116e-01,8.529721e-01,6.613946e-01,1.284671e+00,1.008032e+00,9.960080e-01,1.337922e+00,8.513600e-01,9.088909e-01
max,1.73032,1.685196e+00,3.000238e+00,1.789364e+00,1.708126e+00,2.792595e+00,1.284671e+00,1.008032e+00,9.960080e-01,1.337922e+00,1.688373e+00,1.493011e+00

In [16]:
X_scaled.to_csv("X_scaled.csv", index=False)

y.to_csv("y.csv", index=False)